export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const RECEIVE_PARTNERS = 'RECEIVE_PARTNERS';

export const RECEIVE_TALKS = 'RECEIVE_TALKS';
export const RECEIVE_MORE_TALKS = 'RECEIVE_MORE_TALKS';
export const SET_CURRENT_TALKS_PAGE = 'SET_CURRENT_TALKS_PAGE';
