export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const RECEIVE_PARTNERS = 'RECEIVE_PARTNERS';

export const RECEIVE_TALKS = 'RECEIVE_TALKS';
export const RECEIVE_FILTERED_TALKS = 'RECEIVE_FILTERED_TALKS';
export const RECEIVE_MORE_TALKS = 'RECEIVE_MORE_TALKS';
export const LOADING_TALKS = 'LOADING_TALKS';
export const SET_CURRENT_TALKS_PAGE = 'SET_CURRENT_TALKS_PAGE';

export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_FILTERED_EVENTS = 'RECEIVE_FILTERED_EVENTS';
export const RECEIVE_MORE_EVENTS = 'RECEIVE_MORE_EVENTS';
export const LOADING_EVENTS = 'LOADING_EVENTS';
export const SET_CURRENT_EVENTS_PAGE = 'SET_CURRENT_EVENTS_PAGE';

export const RECEIVE_COPIES = 'RECEIVE_COPIES';
